// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using task_day2.Models;

namespace task_day2.Migrations
{
    [DbContext(typeof(UniversityContext))]
    partial class UniversityContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("task_day2.Models.author", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("authors");
                });

            modelBuilder.Entity("task_day2.Models.news", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("authorid")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("id");

                    b.HasIndex("authorid");

                    b.ToTable("newss");
                });

            modelBuilder.Entity("task_day2.Models.news_details", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("name")
                        .HasColumnType("int");

                    b.Property<int?>("newsid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("newsid");

                    b.ToTable("news_Detailss");
                });

            modelBuilder.Entity("task_day2.Models.news", b =>
                {
                    b.HasOne("task_day2.Models.author", "author")
                        .WithMany("news")
                        .HasForeignKey("authorid");

                    b.Navigation("author");
                });

            modelBuilder.Entity("task_day2.Models.news_details", b =>
                {
                    b.HasOne("task_day2.Models.news", "news")
                        .WithMany("news_details")
                        .HasForeignKey("newsid");

                    b.Navigation("news");
                });

            modelBuilder.Entity("task_day2.Models.author", b =>
                {
                    b.Navigation("news");
                });

            modelBuilder.Entity("task_day2.Models.news", b =>
                {
                    b.Navigation("news_details");
                });
#pragma warning restore 612, 618
        }
    }
}
